<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="DTO\" />
    <Folder Include="Entities\" />
    <Folder Include="Entities\OrderAggregate\" />
    <Folder Include="Extensions\" />
    <Folder Include="Middleware\" />
    <Folder Include="RequestHelper\" />
    <Folder Include="Services\" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
    <PackageReference Include="Stripe.net" Version="51.1.0" />
  </ItemGroup>

</Project>
